Add check for number of TRs

diff --git a/code/recover_from_dup b/code/recover_from_dup
--- a/code/recover_from_dup
+++ b/code/recover_from_dup
@@ -4,6 +4,7 @@ set -eu
 
 tf="$1"
 dup="$2"
+tTRs="$3"  # target number of TRs
 
 
 # need to get json and sbref files too!
@@ -27,6 +28,11 @@ for f in "$tf" "${tf//_bold/_sbref}"; do
                 git annex get "$f2"
             fi
             time=$(jq -r .AcquisitionTime "$f2")
+            nTRs=$(jq -r '.dcmmeta_shape[-1]' "$f2")
+            if [ "$tTRs" != "$nTRs" ]; then
+                echo "ERROR: number of TRs $nTRs is different from target $tTRs. We are not helping here!"
+                exit 1
+            fi
             s="$(dirname $f)/../*_scans.tsv"
             sed -i -e "s|^\([^\t]*/$(basename $f)\t[^\tT]*\)T[^\t]*|\1T$time|g" $s
         fi
